CREATE TABLE IF NOT EXISTS "car_activity" (
    id UUID PRIMARY KEY NOT NULL,
    car_id UUID NOT NULL,
    total_price DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (car_id) REFERENCES car (id) ON DELETE CASCADE ON UPDATE CASCADE
);
